site_name: SnappyData Documentation
site_url: http://www.snappydata.io
site_description: Project documentation for SnappyData
site_author: SnappyData Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- Overview: index.md
# - Introduction: snappyIntroduction.md
- Getting Started: quickstart.md
- Download and Install: install.md
- How Tos: howto.md
- Architecture: architecture.md
- Configuring the Cluster: configuration.md
- Programming Guide: programming_guide.md
- Affinity Modes: deployment.md
- Synopsis Data Engine (SDE): aqp.md
- Using iSight-Cloud: aqp_aws.md
- API: apidocsintro.md
- About:
#   - Release Notes: about/release-notes.md
#   - Contributing: about/contributing.md
    - Contact and Support: techsupport.md
    - License: LICENSE.md

theme: readthedocs

theme_dir: docs/custom_theme

extra_css: [extra.css]

copyright: Copyright &copy; 2016 SnappyData Inc.
