site_name: SnappyData Documentation
site_url: http://www.snappydata.io
site_description: Project documentation with Markdown.
site_author: SnappyData Development Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- SnappyData Overview: index.md
- Introduction: snappyIntroduction.md
- Key features: features.md
- Quick Start Guide: quickstart.md
- Reference Examples: howto.md
- Architecture: architecture.md
- Installing SnappyData: install.md
- Download Binary Distribution: binary.md
- Building from source, project layout: build-instructions.md
- Configuring the Cluster: configuration.md
- Connecting using JDBC, Spark: connectingToCluster.md
- Developing Apps using the Spark API: jobs.md
- Row and Column tables: rowAndColumnTables.md
- Synopsis Data Engine (SDE): aqp.md
- Stream processing using SQL: streamingWithSQL.md
- Deployment topologies: deployment.md
- API: apidocsintro.md
- Using iSight-Cloud: aqp_aws.md
- About:
#   - Release Notes: about/release-notes.md
#   - Contributing: about/contributing.md
    - License: LICENSE.md

theme: readthedocs

extra_css: [extra.css]

copyright: Copyright &copy; 2016 SnappyData Inc.
