site_name: SnappyData Documentation
site_url: http://www.snappydata.io
site_description: Project documentation with Markdown.
site_author: SnappyData Development Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- Overview: index.md
# - Introduction: snappyIntroduction.md
- Getting Started: quickstart.md
- How Tos: howto.md
- Download and Install SnappyData:
    - Instructions: install.md
    - Building from source, project layout: build-instructions.md
- Architecture: architecture.md
- About Cluster:
    - Introduction: cluster.md
    - Configuring the Cluster: configuration.md
    - Using Spark API: clustersparkapi.md
    - Using SQL: clustersql.md
    - Connecting using JDBC, Spark: connectingToCluster.md
- Synopsis Data Engine (SDE): aqp.md
- Developing Apps using the Spark API: jobs.md
- Row and Column tables: rowAndColumnTables.md
- Stream processing using SQL: streamingWithSQL.md
- Deployment topologies: deployment.md
- API: apidocsintro.md
- Using iSight-Cloud: aqp_aws.md
- About:
#   - Release Notes: about/release-notes.md
#   - Contributing: about/contributing.md
    - Contact and Support: techsupport.md
    - License: LICENSE.md

theme: readthedocs

extra_css: [extra.css]

copyright: Copyright &copy; 2016 SnappyData Inc.h
