site_name: SnappyData Documentation
site_url: http://www.snappydata.io
site_description: Project documentation for SnappyData
site_author: SnappyData Team
site_favicon: favicon.ico

repo_url: https://github.com/SnappyDataInc/snappydata

pages:
# this file may just be the [toc] tag .. not sure if that works.
#
- Overview: index.md
# - Introduction: snappyIntroduction.md
- 'Getting Started in 5 minutes or Less': 'quickstart.md'
- 'Getting Started in 5 minutes or Less': 
    - 'Getting Started with your Spark Distribution': 'quickstart/getting_started_with_your_spark_distribution.md'
    - 'Getting Started by Installing SnappyData On-Premise': 'quickstart/getting_started_by_installing_snappydata_on-premise.md'
    - 'Getting Started with Amazon Web Services': 'quickstart/getting_started_on_aws.md'
    - 'Getting Started with Docker Image': 'quickstart/getting_started_with_docker_image.md'
#    - 'Getting Started with Snappy JDBC Streaming Connector': 'quickstart/getting_started_jdbc_streaming_connector.md'
    - 'Getting Started with SnappyData GemFire Connector': 'quickstart/getting_started_gemfire_connector.md'    
    - 'Using Spark Scala APIs': 'quickstart/using_spark_scala_apis.md'
    - 'SnappyData Performance:16x-20x faster than Apache Spark': 'quickstart/performance_apache_spark.md'
    - 'Using SQL': 'quickstart/using_sql.md'
- 'Download and Install': 'install.md'
- 'Download and Install':
    - System Requirements: 'install/system_requirements.md'
    - 'Install On-Premise': 'install/install_on_premise.md'
    - 'Setting up Cluster on Amazon Web Services': 'install/setting_up_cluster_on_amazon_web_services.md'
    - 'Building from Source': 'install/building_from_source.md'
#- 'Migration Guide': 'migration/migration.md'
#- 'Migration Guide':
#    - 'Manually Upgrading from GemFire XD 1.4.x to SnappyData RowStore 1.0': 'migration/upgrade_gemfirexd_standalone.md'
#    - 'Manually Upgrading from SQLFire 1.1.x to SnappyData RowStore 1.0': 'migration/upgrade_sqlfire_standalone.md'    
#    - 'Migrating from Version 0.8 to Version 0.9': 'migration/migration-0.8-0.9.md'
#    - 'Migrating from Version 0.9 to Version 1.0.0-RC1 Release': 'migration/migration-0.9-01_rc.md'
#---
- 'How Tos': 'howto.md'
- 'How Tos': 
    - 'How to Start a SnappyData Cluster': 'howto/start_snappy_cluster.md'
    - 'How to check the Status of a SnappyData Cluster': 'howto/check_status_cluster.md'
    - 'How to Stop a SnappyData Cluster': 'howto/stop_snappy_cluster.md'
    - 'How to Run Spark Job inside the Cluster': 'howto/run_spark_job_inside_cluster.md'
    - 'How to Access SnappyData Store from existing Spark Installation using Smart Connector': 'howto/spark_installation_using_smart_connector.md'
    - 'How to Use Snappy SQL shell (snappy-sql)': 'howto/use_snappy_shell.md'
    - 'How to Create Row Tables and Run Queries': 'howto/create_row_tables_and_run_queries.md'
    - 'How to Create Column Tables and Run Queries': 'howto/create_column_tables_and_run_queries.md'
    - 'How to Load Data into SnappyData Tables': 'howto/load_data_into_snappydata_tables.md'
    - 'How to Load Data from External Data Stores (e.g. HDFS, Cassandra, Hive, etc)': 'howto/load_data_from_external_data_stores.md'
    - 'How to Perform a Colocated Join': 'howto/perform_a_colocated_join.md'
    - 'How to Connect using JDBC Driver': 'howto/connect_using_jdbc_driver.md'
    - 'How to Store and Query JSON Objects': 'howto/store_and_query_json_objects.md'
    - 'How to Store and Query Objects': 'howto/store_and_query_objects.md'
    - 'How to use Stream Processing with SnappyData': 'howto/use_stream_processing_with_snappydata.md'
    - 'How to use Transactions Isolation Levels': 'howto/use_transactions_isolation_levels.md'
    - 'How to use Synopsis Data Engine to Run Approximate Queries': 'howto/use_synopsis_data_engine_to_run_approximate_queries.md'
    - 'How to use Python to Create Tables and Run Queries': 'howto/use_python_to_create_tables_and_run_queries.md'
    - 'How to Connect using ODBC Driver': 'howto/connect_using_odbc_driver.md'
    - 'How to Connect to the Cluster from External Network': 'howto/connect_to_the_cluster_from_external_clients.md'
    - 'How to Import Data from Hive Table into SnappyData Table': 'howto/import_from_hive_table.md'    
    - 'How to Export and Restore Table Data using HDFS': 'howto/export_hdfs.md'    
    - 'How to Use Apache Zeppelin with SnappyData': 'howto/use_apache_zeppelin_with_snappydata.md'
- 'Architecture': 'architecture.md'
- 'Architecture': 
    - 'Core Components': 'architecture/core_components.md'
    - 'Data Ingestion Pipeline': 'architecture/data_ingestion_pipeline.md'
    - 'Hybrid Cluster Manager': 'architecture/hybrid_cluster_manager.md'
    - 'SnappyData Cluster Architecture': 'architecture/cluster_architecture.md'    
- 'Configuring the Cluster': 'configuration.md'
- 'Configuring the Cluster':
    - 'Configuration': 'configuring_cluster/configuring_cluster.md'
    - 'SSL Setup for Client-Server': 'configuring_cluster/ssl_setup.md'
    - 'List of Properties': 'configuring_cluster/property_description.md'
- 'Programming Guide': 'programming_guide.md'
- 'Programming Guide':
    - 'SparkSession, SnappySession and SnappyStreamingContext': 'programming_guide/sparksession_snappysession_and_snappystreamingcontext.md'
    - 'SnappyData Jobs': 'programming_guide/snappydata_jobs.md'
    - 'Managing JAR Files': 'programming_guide/managing_jar_files.md'
    - 'Using SnappyData Shell': 'programming_guide/using_snappydata_shell.md'
    - 'Using the Spark Shell and spark-submit': 'programming_guide/using_the_spark_shell_and_spark-submit.md'
    - 'Working with Hadoop YARN cluster Manager': 'programming_guide/working_with_hadoop_yarn_cluster_manager.md'
    - 'Using Transactions': 'programming_guide/using_transactions.md'
    - 'Using JDBC with SnappyData': 'programming_guide/using_jdbc_with_snappydata.md'
    - 'Multiple Language Binding using Thrift Protocol': 'programming_guide/multiple_language_binding_using_thrift_protocol.md'
    - 'Building SnappyData Applications using Spark API': 'programming_guide/building_snappydata_applications_using_spark_api.md'
    - 'Tables in SnappyData': 'programming_guide/tables_in_snappydata.md'
    - 'Stream Processing using SQL': 'programming_guide/stream_processing_using_sql.md'
    - 'User Defined Functions (UDF) and User Defined Aggregate Functions (UDAF)': 'programming_guide/udf_and_udaf.md' 
- 'Affinity Modes': 'deployment.md'
- 'Affinity Modes': 
    - 'Local Mode': 'affinity_modes/local_mode.md'
    - 'Embedded SnappyData Store Mode': 'affinity_modes/embedded_mode.md'
    - 'SnappyData Smart Connector Mode': 'affinity_modes/connector_mode.md'
- 'Best Practices': 'best_practices.md'
- 'Best Practices':
    - 'Tuning for Concurrency and Computation': 'best_practices/setup_cluster.md'
    - 'Designing your Database and Schema': 'best_practices/design_schema.md'  
    - 'Designing your Database and Schema':
        - 'Design Principles of Scalable, Partition-Aware Databases': 'best_practices/design_principles.md'  
        - 'Optimizing Query Latency: Partitioning and Replication Strategies': 'best_practices/optimizing_query_latency.md'
    - 'Memory Management': 'best_practices/memory_management.md'      
    - 'HA Considerations': 'best_practices/ha_considerations.md'    
    - 'Important Settings': 'best_practices/important_settings.md'
- 'Synopsis Data Engine (SDE)': 'aqp.md'
- 'Synopsis Data Engine (SDE)': 
    - 'Key Concepts': 'sde/key_concepts.md'
    - 'Working with Stratified Samples': 'sde/working_with_stratified_samples.md'
    - 'Running Queries': 'sde/running_queries.md'
    - 'More Examples': 'sde/more_examples.md'
    - 'Sample Selection': 'sde/sample_selection.md'
    - 'High-level Accuracy Contracts (HAC)': 'sde/hac_contracts.md'
    - 'Sketching': 'sde/sketching.md'
- 'Using SnappyData CloudBuilder': 'aqp_aws.md'
- 'Using SnappyData CloudBuilder': 
    - 'Key Components': 'isight/key_components.md'
    - 'Quick Start Steps': 'isight/quick_start_steps.md'
    - 'The Technology Powering SnappyData CloudBuilder': 'isight/the_technology_powering_isight_cloud.md'
- 'Managing and Monitoring': 'monitoring/managing_and_monitoring.md'
- 'Managing and Monitoring':
    - 'SnappyData Pulse': 'monitoring/monitoring.md'
    - 'Configuring High Availability for a Partitioned Table': 'monitoring/configure_high_availability.md'    
    - 'Configuring Logging': 'monitoring/configure_logging.md'
# -- Topic - Reference Guide
- 'Managing Security': 'security/security.md'
- 'Managing Security': 
    - 'Launching the Cluster in Secure Mode': 'security/launching_the_cluster_in_secure_mode.md'
    - 'Authentication - Connecting to a Secure Cluster': 'security/authentication_connecting_to_a_secure_cluster.md'
    - 'Authorization': 'security/authorization.md'
    - 'Configuring Network Encryption and Authentication using SSL': 'security/configuring_network_encryption_and_authentication_using_ssl.md'
    - 'User Names for Authentication, Authorization, and Membership': 'security/user_names_for_authentication_authorization_and_membership.md'
- 'Reference Guides': 'reference.md'
- 'Reference Guides': 
    - 'SQL Reference Guide': 'sql_reference.md'
    - 'SQL Reference Guide':
        - 'ALTER TABLE': 'reference/sql_reference/alter-table.md'    
        - 'CREATE Statements': 'reference/sql_reference/create-statements.md'
        - 'CREATE Statements':
            - 'CREATE DISKSTORE': 'reference/sql_reference/create-diskstore.md'
            - 'CREATE FUNCTION': 'reference/sql_reference/create-function.md'
            - 'CREATE INDEX': 'reference/sql_reference/create-index.md'
            - 'CREATE SCHEMA': 'reference/sql_reference/create-schema.md'
            - 'CREATE TABLE': 'reference/sql_reference/create-table.md'
            - 'CREATE SAMPLE TABLE': 'reference/sql_reference/create-sample-table.md'
            - 'CREATE EXTERNAL TABLE': 'reference/sql_reference/create-external-table.md'
            - 'CREATE TEMPORARY TABLE': 'reference/sql_reference/create-temporary-table.md'
            - 'CREATE STREAM TABLE': 'reference/sql_reference/create-stream-table.md'
        - 'DELETE': 'reference/sql_reference/delete.md'
        - 'DROP Statements': 'reference/sql_reference/drop-statements.md'
        - 'DROP Statements':
            - 'DROP DISKSTORE': 'reference/sql_reference/drop-diskstore.md'
            - 'DROP FUNCTION': 'reference/sql_reference/drop-function.md'
            - 'DROP INDEX': 'reference/sql_reference/drop-index.md'
            - 'DROP TABLE': 'reference/sql_reference/drop-table.md'
        - 'GRANT': 'reference/sql_reference/grant.md'
        - 'INSERT': 'reference/sql_reference/insert.md'
        - 'PUT INTO': 'reference/sql_reference/put-into.md'
        - 'REVOKE': 'reference/sql_reference/revoke.md'
        - 'SELECT': 'reference/sql_reference/select.md'
        - 'SET ISOLATION': 'reference/sql_reference/set-isolation.md'
        - 'SET SCHEMA': 'reference/sql_reference/set-schema.md'
        - 'TRUNCATE TABLE': 'reference/sql_reference/truncate-table.md'
        - 'UPDATE': 'reference/sql_reference/update.md'
    - 'Built-in System Procedures and Built-in Functions': 'reference/inbuilt_system_procedures/system-procedures.md'
    - 'Built-in System Procedures and Built-in Functions': 
        - 'DUMP_STACKS': 'reference/inbuilt_system_procedures/dump-stacks.md'
        - 'REBALANCE_ALL_BUCKETS': 'reference/inbuilt_system_procedures/rebalance-all-buckets.md'
        - 'SET_CRITICAL_HEAP_PERCENTAGE': 'reference/inbuilt_system_procedures/set_critical_heap_percentage.md'
#        - 'SET_EVICTION_HEAP_PERCENTAGE': 'reference/inbuilt_system_procedures/set_eviction_heap_percentage.md'
        - 'SET_TRACE_FLAG': 'reference/inbuilt_system_procedures/set-trace-flag.md'
        - 'DSID': 'reference/inbuilt_system_procedures/dsid.md'
    - 'System Tables': 'reference/system_tables/system_tables.md'
    - 'System Tables': 
        - 'MEMBERS': 'reference/system_tables/members.md'
        - 'MEMORYANALYTICS': 'reference/system_tables/memoryanalytics.md'    
        - 'SYSDISKSTORES': 'reference/system_tables/sysdiskstores.md'    
        - 'SYSTABLES': 'reference/system_tables/systables.md'    
    - 'Command Line Utilities': 'reference/command_line_utilities/store-launcher.md'
    - 'Command Line Utilities':
        - 'backup and restore': 'reference/command_line_utilities/store-backup.md'
        - 'compact-all-disk-stores': 'reference/command_line_utilities/store-compact-all-disk-stores.md'
        - 'compact-disk-store': 'reference/command_line_utilities/store-compact-disk-store.md'
        - 'list-missing-disk-stores': 'reference/command_line_utilities/store-list-missing-disk-stores.md'
        - 'revoke-missing-disk-store': 'reference/command_line_utilities/store-revoke-missing-disk-stores.md'
        - 'run': 'reference/command_line_utilities/store-run.md'
        - 'version': 'reference/command_line_utilities/store-version.md'
    - 'Snappy-SQL Shell Interactive Commands': 'reference/interactive_commands/store_command_reference.md'
    - 'Snappy-SQL Shell Interactive Commands':
        - 'autocommit': 'reference/interactive_commands/autocommit.md'
        - 'commit': 'reference/interactive_commands/commit.md'
        - 'connect client': 'reference/interactive_commands/connect_client.md'
        - 'connect': 'reference/interactive_commands/connect.md'
        - 'describe': 'reference/interactive_commands/describe.md'
        - 'disconnect': 'reference/interactive_commands/disconnect.md'
        - 'elapsedtime': 'reference/interactive_commands/elapsedtime.md'
        - 'exit': 'reference/interactive_commands/exit.md'
        - 'MaximumDisplayWidth': 'reference/interactive_commands/maximumdisplaywidth.md'
        - 'rollback': 'reference/interactive_commands/rollback.md'
        - 'run': 'reference/interactive_commands/run.md'
        - 'set connection': 'reference/interactive_commands/set_connection.md'
        - 'show': 'reference/interactive_commands/show.md'
    - 'Configuration Parameters': 'reference/configuration_parameters/config_parameters.md'
    - 'Configuration Parameters':         
        - 'ack-severe-alert-threshold': 'reference/configuration_parameters/ack-severe-alert-threshold.md'
        - 'ack-wait-threshold': 'reference/configuration_parameters/ack-wait-threshold.md'
        - 'archive-disk-space-limit': 'reference/configuration_parameters/archive-disk-space-limit.md'
        - 'archive-file-size-limit': 'reference/configuration_parameters/archive-file-size-limit.md'
        - 'bind-address': 'reference/configuration_parameters/bind-address.md'
        - 'enable-network-partition-detection': 'reference/configuration_parameters/enable-network-partition-detection.md'
        - 'enable-stats': 'reference/configuration_parameters/enable-stats.md'
        - 'enable-time-statistics': 'reference/configuration_parameters/enable-time-statistics.md'
        - 'enforce-unique-host': 'reference/configuration_parameters/enforce-unique-host.md'
        - 'init-scripts': 'reference/configuration_parameters/init-scripts.md'
        - 'locators': 'reference/configuration_parameters/locators.md'
#        - 'log-disk-space-limit': 'reference/configuration_parameters/log-disk-space-limit.md'
        - 'log-file': 'reference/configuration_parameters/log-file.md'
#        - 'log-file-size-limit': 'reference/configuration_parameters/log-file-size-limit.md'
        - 'log-level': 'reference/configuration_parameters/log-level.md'
        - 'member-timeout': 'reference/configuration_parameters/member-timeout.md'
#        - 'membership-port-range': 'reference/configuration_parameters/membership-port-range.md'
#        - 'persist-dd': 'reference/configuration_parameters/persist-dd.md'
#        - 'prefer-netserver-ipaddress': 'reference/configuration_parameters/prefer-netserver-ipaddress.md'
#        - 'read-timeout': 'reference/configuration_parameters/read-timeout.md'
        - 'redundancy-zone': 'reference/configuration_parameters/redundancy-zone.md'
#        - 'secondary-locators': 'reference/configuration_parameters/secondary-locators.md'
#        - 'shutdown': 'reference/configuration_parameters/shutdown.md'
#        - 'skip-constraint-checks': 'reference/configuration_parameters/skip-constraint-checks.md'
#        - 'skip-listeners': 'reference/configuration_parameters/skip-listeners.md'
#        - 'skip-locks': 'reference/configuration_parameters/skip-locks.md'
#        - 'socket-buffer-size': 'reference/configuration_parameters/socket-buffer-size.md'
#        - 'socket-lease-time': 'reference/configuration_parameters/socket-lease-time.md'
#        - 'snappydata.datadictionary.allow-startup-errors': 'reference/configuration_parameters/snappydata.datadictionary.allow-startup-errors.md'
#        - 'snappydata.default-startup-recovery-delay': 'reference/configuration_parameters/snappydata.default-startup-recovery-delay.md'
#        - 'snappy.history': 'reference/configuration_parameters/snappy.history.md'
#        - 'snappydata.max-lock-wait': 'reference/configuration_parameters/snappydata.max-lock-wait.md'
#        - 'gemfirexd.properties': 'reference/configuration_parameters/gemfirexd.properties.md'
#        - 'snappydata.query-cancellation-interval': 'reference/configuration_parameters/snappydata.query-cancellation-interval.md'
#        - 'snappydata.query-timeout': 'reference/configuration_parameters/snappydata.query-timeout.md'
#        - 'snappydata.storage.tempDirectory': 'reference/configuration_parameters/snappydata.storage.tempDirectory.md'
#        - 'snappydata.system.home': 'reference/configuration_parameters/snappydata.system.home.md'
        - 'start-locator': 'reference/configuration_parameters/start-locator.md'
        - 'statistic-archive-file': 'reference/configuration_parameters/statistic-archive-file.md'
        - 'statistic-sample-rate': 'reference/configuration_parameters/statistic-sample-rate.md'
        - 'statistic-sampling-enabled': 'reference/configuration_parameters/statistic-sampling-enabled.md'
        - 'sys-disk-dir': 'reference/configuration_parameters/sys-disk-dir.md'
#        - 'tcp-port': 'reference/configuration_parameters/tcp-port.md'
        - 'user': 'reference/configuration_parameters/user.md'
    - 'API Documentation': 'apidocsintro.md'
#    - 'Supported Data Types': 'reference/misc/supported_datatypes.md'
    - 'Configuring SSH Login without Password': 'reference/misc/passwordless_ssh.md'
    - 'Setting Up SnappyData ODBC Driver and Tableau Desktop': 'setting_up_odbc_driver-tableau_desktop.md' 
- 'Troubleshooting Common Problems': 'troubleshooting/troubleshooting.md'
- 'Troubleshooting Common Problems':
    - 'Member Startup Problems': 'troubleshooting/member_startup_problems.md'
    - 'Recovering from a ConflictingPersistentDataException': 'troubleshooting/recovering_from_a_conflictingpersistentdataexception.md'
    - 'Preventing Disk Full Errors': 'troubleshooting/preventing_disk_full_errors.md'
    - 'Recovering from Disk Full Errors': 'troubleshooting/recovering_from_disk_full_errors.md'
    - 'Troubleshooting Error Messages': 'troubleshooting/troubleshooting_error_messages.md'
- Additional Information: additional_files/additional_docs.md
#- About:
#   - Contributing: about/contributing.md
- Community Edition/ Enterprise Edition Features: additional_files/open_source_components.md
- 'License Model': 'additional_files/license_model.md'
#- 'Release Notes': 'release_notes/release_notes_1.0.md'
#- 'Release Notes': 
#    - 'Known Issues': 'release_notes/known_issues.md'
- Contact and Support: techsupport.md
- License: LICENSE.md

theme: readthedocs
theme_dir: 'docs/custom_theme'

extra_javascript:
  - 'js/menu.js'

extra_css:
    - 'css/toc.css'
    - 'css/menu.css'
    - 'css/images.css'
    - 'css/style.css'
    - 'extra.css'
    
markdown_extensions:
    - admonition:
   
    
copyright: Copyright &copy; 2017 SnappyData Inc.
